### ISSUE TITLE
Amatrix function does not account for double reduction when ploidy > 4

### ISSUE THREAD

**Issue by tpbilton** [prmunoz/AGHmatrix#18]
It seems that when one computes the A matrix using the **Amatrix** function, that double reduction is only accounted for in tetraploid but not for higher polyploids. I was wanting to compute the A matrix for a hexaploid with double reduction. Is there a reason why this hasn't be implemented in AGHmatrix yet (e.g., too hard)? 

Thanks,
Timothy

**Comment by rramadeu** [comment]
Hi Timothy, thanks for using the AGHmatrix!!

I've just implemented the double-reduction for ploidies higher than 4 as Kerr et al. (2012). Please, take a look at it. Let me know if you find any other issue with the package.

To use it:

```
devtools::install_github("prmunoz/AGHmatrix")
library(AGHmatrix)
data(ped.mrode)
Amatrix(ped.mrode, ploidy=6, w=0)
Amatrix(ped.mrode, ploidy=6, w=0.1)
```

ps.: by the way, which species are you working with?

Best,
Rodrigo
