### ISSUE TITLE
Error message with Amatrix function

### ISSUE THREAD

**Issue by tpbilton** [prmunoz/AGHmatrix#27]
Hi There,

I was trying to compute an A matrix for quite a complicated pedigree and was getting an error message. I have a reproduced a minimum working example on some mocked up data that kind of reflects my real data below.

```
ped <- read.table("test_ped.txt", header=T, stringsAsFactors=F, sep="\t")
Amatrix(ped, ploidy=4)
Error in if (is.na(match(parent[j], ind[1:j])) && parent[j] != 0) { :
  missing value where TRUE/FALSE needed
```

I have attached the file [test_ped.txt](https://github.com/prmunoz/AGHmatrix/files/2980889/test_ped.txt). The species I'm working with is Potato which have quite complex pedigrees.

Thanks,
Timothy

**Comment by rramadeu** [comment]
Hi Timothy,

Thanks for contacting us,

The AGHmatrix has some problems in reordering some specific pedigrees, Usually, this error raises when the pedigree is not chronologically ordered and the internal algorithm to reorder crashes. I need to improve it...

I reordered your pedigree by hand, putting your base population genotypes in the top, and then the first offsprings, and so on.. It follows the code and the pedigree reordered, it has the same pedigree information and now the Amatrix computation works.

I hope it solves your issue,

Best,
Rodrigo

Code:
```
library(AGHmatrix)
ped <- read.table("test_ped.txt", header=T, stringsAsFactors=F, sep="\t")
Amat <- Amatrix(ped)

original_order <- match(paste0("I",1:29),rownames(Amat))
Amat <- Amat[original_order,original_order]

```


Pedigree:

Ind	Par1	Par2
I18	0	0
I19	0	0
I20	0	0
I21	0	0
I22	0	0
I24	0	0
I25	0	0
I26	0	0
I28	0	0
I29	0	0
I27	0	I21
I15	I20	I20
I17	I24	I21
I23	I17	0
I14	I25	I24
I13	I25	I24
I16	I24	I23
I11	I15	I19
I12	I16	I19
I1	I11	I12
I2	I11	I14
I3	I13	I15
I4	I16	I18
I5	I17	I12
I6	I18	I21
I7	I26	I22
I8	I27	I28
I9	I29	I12
I10	I11	I12

**Comment by tpbilton** [comment]
Hi Rodrigo,

Thanks for replying and clarifying the situation. I'll have a go at doing the sorting manual then. It just would be nice if AGHmatrix could do this automatically for us. Maybe a feature for a future release?

Cheers,
Timothy

**Comment by rramadeu** [comment]
Hi Timothy,

Yes, it is a feature for a future release. Probably with your small example, I'd be able to identify when the actual sorting algorithm is crashing...
Thanks,
Rodrigo

**Comment by rramadeu** [comment]
Hi Timothy,

I found an easy solution and just implemented.

(I had an old and slow but consistent algorithm to reorder, now if the new one crashes the Amatrix function uses the older algorithm to try to reorder)

Please let me know if now you can build the A matrix with your original pedigree file. In order to use it you'll need to install the new development version of the package.

```
library(devtools)
install_github("prmunoz/AGHmatrix")
```

Cheers, 
Rodrigo

**Comment by tpbilton** [comment]
Hi Rodrigo,

I have given this a try today and it seems to work. I came up with my own way of reordering and got the same answer as your solution, so nice that Amatrix can handle unordered pedigrees properly :)

Thanks for implementing this. When will push the new changes to CRAN?

Timothy

**Comment by rramadeu** [comment]
Hi Timothy, I just pushed on CRAN, now the CRAN and this github version (0.05) are synchronized. Please let me know if you find any new bugs with the CRAN version. Thanks for all the help/reports,
I'm closing this thread,
Cheers,
Rodrigo
