### ISSUE TITLE
Default value of the maf parameter is not the same in the help and in the code

### ISSUE THREAD

**Issue by JulietteArchambeau** [prmunoz/AGHmatrix#35]
https://github.com/prmunoz/AGHmatrix/blob/b9802fd6af9497b29b9a9bee4d48256535c730b0/R/Gmatrix.R#L25

In your code, default of maf parameter is 0 and in the help, default is 0.05.

**Comment by rramadeu** [comment]
Hi Juliette, thanks for the heads up! I just fixed, the CRAN version will be fixed in the next update.
