### ISSUE TITLE
Possible bug related to mean imputation resulting in higher than expected GRM values

### ISSUE THREAD

**Issue by timothymillar** [prmunoz/AGHmatrix#44]
Hi all, thanks for AGHmatrix,

I've discovered what I believe is a bug when calculating the VanRaden GRM with mean imputation resulting in higher than expected relatedness. This seems to be the result of how NA values are handled and is caused by the combination of two sections of code:
- Calling `snp.check` with `impute.method="mean"` on the `SNPmatrix` [here](https://github.com/prmunoz/AGHmatrix/blob/master/R/Gmatrix.R#L107) which replaces NA values via mean imputation
- Calculating allele frequencies [here](https://github.com/prmunoz/AGHmatrix/blob/master/R/Gmatrix.R#L133) with a function which appears to expect *only* integer values (0,1,2 for diploids) and NA values for missing data.

The issue is that, by the time the allele frequencies are calculated, the NA values have already been replaced with floating point values via mean imputation in `snp.check`. These imputed values (generally) do not match 0,1 or 2 so they aren't added to either numerator, but they are also no longer NA so they don't get excluded from the denominator correctly. This results in frequencies which don't sum to 1.

Here is an example following the relevant sections of code (I think I got them all) step by step:
```r
library(AGHmatrix)
data(snp.pine)
SNPmatrix = snp.pine

m <- match(SNPmatrix, -9, 0)
SNPmatrix[m > 0] <- NA

sum(is.na(SNPmatrix)) # = 170472
SNPmatrix <- AGHmatrix:::snp.check(
    SNPmatrix,
   ploidy = 2, 
   thresh.maf = 0.0, 
   thresh.missing = 1,
   impute.method = "mean"
)
# NA values replaced by mean imputation
sum(is.na(SNPmatrix)) # = 0

alelleFreq <- function(x, y) {
  (2 * length(which(x == y)) + length(which(x == 1)))/(2 * length(which(!is.na(x))))
}

Frequency <- cbind(
    apply(SNPmatrix, 2, function(x) alelleFreq(x,0)), 
    apply(SNPmatrix, 2, function(x) alelleFreq(x, 2))
)
# these should sum to 1 for every locus but
min(Frequency[,1] + Frequency[,2]) # = 0.0118790496760259

FreqP <- matrix(rep(Frequency[, 2], each = nrow(SNPmatrix)), ncol = ncol(SNPmatrix))
  
TwoPQ <- 2 * t(Frequency[, 1]) %*% Frequency[, 2]
SNPmatrix <- SNPmatrix- 2 * FreqP

# this line appears to be equivalent to mean imputation but does nothing because NAs have already been replaced
SNPmatrix[is.na(SNPmatrix)] <- 0

Gmatrix <- (tcrossprod(SNPmatrix, SNPmatrix))/as.numeric(TwoPQ)
max(Gmatrix) # = 1.23775244802804
min(Gmatrix) # = -0.0729135509172718
```

This matches the output of:
```r
library(AGHmatrix)
data(snp.pine)
GRM <- Gmatrix(
    SNPmatrix=snp.pine,
    missingValue=-9, 
    maf=0.0,
    method="VanRaden",
)
max(GRM) # = 1.23775244802804
min(GRM) # = -0.0729135509172718
```

If I remove the call to `snp.check` then I get what I ***think*** is the correct result based on independent calculation:
```r
library(AGHmatrix)
data(snp.pine)
SNPmatrix = snp.pine

m <- match(SNPmatrix, -9, 0)
SNPmatrix[m > 0] <- NA

# No imputation so NAs remain
sum(is.na(SNPmatrix)) # = 170472

alelleFreq <- function(x, y) {
  (2 * length(which(x == y)) + length(which(x == 1)))/(2 * length(which(!is.na(x))))
}

Frequency <- cbind(
    apply(SNPmatrix, 2, function(x) alelleFreq(x,0)), 
    apply(SNPmatrix, 2, function(x) alelleFreq(x, 2))
)
# these should sum to 1 for every locus
min(Frequency[,1] + Frequency[,2]) # = 1
max(Frequency[,1] + Frequency[,2]) # = 1

FreqP <- matrix(rep(Frequency[, 2], each = nrow(SNPmatrix)), ncol = ncol(SNPmatrix))
  
TwoPQ <- 2 * t(Frequency[, 1]) %*% Frequency[, 2]
SNPmatrix <- SNPmatrix- 2 * FreqP

# this effectively performs mean imputation
SNPmatrix[is.na(SNPmatrix)] <- 0

Gmatrix <- (tcrossprod(SNPmatrix, SNPmatrix))/as.numeric(TwoPQ)
max(Gmatrix) # = 1.06730135345408
min(Gmatrix) # = -0.137861902022916
```
Note that the max and  min values of the matrix are much lower than in the first example.

And the independent calculation in python:
```python
import numpy as np
import pandas as pd

# read pine dataset saved from AGHmatrix
snps = pd.read_csv("snp.pine.csv", index_col=0).values.astype(float)
snps[snps == -9] = np.nan
np.isnan(snps).sum()  # = 170472

# following VanRaden use population mean frequencies
M = snps - 1
f = np.nanmean(snps, axis=0) / 2
P = (np.nanmean(snps, axis=0) - 1)[None,:]
Z = M - P
Z[np.isnan(Z)] = 0  # mean impuation on mean centered data
G = (Z @ Z.T) / (2 * (f * (1-f)).sum())
G.max() # = 1.067301353454077
G.min() # = -0.13786190202291643
```

**Comment by rramadeu** [comment]
Hi Tim,

I apoligize the delay to track this issue, the main AGHmatrix repo is at rramadeu/AGHmatrix.

I don`t see this as a bug since the order of imputing first and getting the frequencies, or the opposite it is not set in stone. And such order doesn`t impact the results dramatically. Yes, the values are different, but highly correlated which would not impact downstream analysis anyhow.

`
cor(Gmatrix[lower.tri(Gmatrix)],GRM[lower.tri(GRM)]) #.9977

#or
`
plot(diag(Gmatrix),diag(GRM))
cor(diag(Gmatrix),diag(GRM))
`

A solution close to what you are proposing is to use the ratio option as:
`
GRM2 <- Gmatrix(
  SNPmatrix=snp.pine/2,
  missingValue=-4.5, 
  ploidy=2,
  maf=0.0,
  ratio=TRUE,
  method="VanRaden",
)
`

It would not result the same output given the other difference of the script.

Thanks,
Rodrigo

**Comment by timothymillar** [comment]
Hi @rramadeu , thanks for following up. Sorry I reported this on the wrong fork.

I agree that the order of imputation and calculating frequencies shouldn't matter. in fact, mean imputation shouldn't change the mean allele frequency at all.

The issue is how the allele frequencies are calculated after mean imputation. The `alelleFreq` function seems to be ignoring imputed dosages when it calculates the numerator, but counting them when it calculates the denominator. This results in incorrect scaling of the relationship matrix. The degree depends on the number of imputed values that are not exact integers.

In the following example I have two identical SNP matrices except for three missing values in the second matrix. These missing values (intentionally) don't change the mean allele frequency and therefore shouldn't change the estimated relationships among the first three samples (which have complete data). But the returned relationships between the first three samples differ:

```r
library(AGHmatrix)
snpsA = as.matrix(rbind(c(0,1,1,0,0,1,1,0),
                        c(1,1,1,1,2,1,1,0),
                        c(1,0,0,2,1,1,1,1),
                        c(0,1,1,0,1,0,1,0),
                        c(0,2,0,1,0,1,0,0),
                        c(1,2,2,1,0,0,0,1)))

snpsB = as.matrix(rbind(c(0,1,1,0,0,1,1,0),  # identical matrix with some missing values
                        c(1,1,1,1,2,1,1,0),
                        c(1,0,0,2,1,1,1,1),
                        c(0,1,1,0,1,0,1,NA),
                        c(0,2,0,1,0,1,0,NA),
                        c(1,2,2,1,0,0,0,NA)))

# note that mean allele frequencies are the same:
colMeans(snpsA)
# 0.51.166666666666670.8333333333333330.8333333333333330.6666666666666670.6666666666666670.6666666666666670.333333333333333
colMeans(snpsB, na.rm=TRUE)
# 0.51.166666666666670.8333333333333330.8333333333333330.6666666666666670.6666666666666670.6666666666666670.333333333333333

Gmatrix(snpsA, maf=0.0, method="VanRaden")
# 0.51612903   -0.25806452   -0.4032258    0.22580645    0.08064516    -0.16129032
#-0.25806452    0.70967742    0.2741935    0.03225806   -0.40322581    -0.35483871
#-0.40322581    0.27419355    1.2903226   -0.40322581   -0.25806452    -0.50000000
# 0.22580645    0.03225806   -0.4032258    0.51612903   -0.20967742    -0.16129032
# 0.08064516   -0.40322581   -0.2580645   -0.20967742    0.80645161    -0.01612903
#-0.16129032   -0.35483871   -0.5000000   -0.16129032   -0.01612903     1.19354839

Gmatrix(snpsB, maf=0.0, method="VanRaden")
# 0.52360515   -0.300429185   -0.4034335    0.197424893    0.04291845   -0.11158798
#-0.30042918    0.729613734    0.3175966   -0.008583691   -0.47210300   -0.31759657
#-0.40343348    0.317596567    1.4506438   -0.317596567   -0.16309013   -0.62660944
# 0.19742489   -0.008583691   -0.3175966    0.523605150   -0.24892704   -0.09442060
# 0.04291845   -0.472103004   -0.1630901   -0.248927039    0.83261803    0.06008584
#-0.11158798   -0.317596567   -0.6266094   -0.094420601    0.06008584    1.14163090
```

If I recalculate this using colMeans to compute the allele frequencies, then we see that the missing values don't affect the relationships for the first three samples:

```r
diploidVanRaden <- function(snps, impute=FALSE) {
    if (impute) {
        for(i in 1:ncol(snps)){
          snps[is.na(snps[,i]), i] <- mean(snps[,i], na.rm = TRUE)
        }
    }
    M = snps - 1
    f = colMeans(snps, na.rm=TRUE) / 2  # allele frequencies
    P = t(replicate(nrow(snps), colMeans(snps, na.rm=TRUE) - 1))
    Z = M - P
    tcrossprod(Z, Z) / (2 * sum(f * (1 - f)))
}

diploidVanRaden(snpsB)
# 0.5161290   -0.2580645   -0.4032258    NA    NA    NA
#-0.2580645    0.7096774    0.2741935    NA    NA    NA
#-0.4032258    0.2741935    1.2903226    NA    NA    NA
# NA           NA           NA           NA    NA    NA
# NA           NA           NA           NA    NA    NA
# NA           NA           NA           NA    NA    NA

diploidVanRaden(snpsB, impute=TRUE)
# 0.51612903   -2.580645e-01   -0.4032258    1.935484e-01    0.0483871   -0.09677419
#-0.25806452    7.096774e-01    0.2741935    3.715666e-17   -0.4354839   -0.29032258
#-0.40322581    2.741935e-01    1.2903226   -3.387097e-01   -0.1935484   -0.62903226
# 0.19354839    3.715666e-17   -0.3387097    4.838710e-01   -0.2419355   -0.09677419
# 0.04838710   -4.354839e-01   -0.1935484   -2.419355e-01    0.7741935    0.04838710
#-0.09677419   -2.903226e-01   -0.6290323   -9.677419e-02    0.0483871    1.06451613


```
